actions/stale

action.yml
Fix typo 'iusses' -> 'issues'.  Also update 'prs' to 'pull requests'.
=> Spelling fixes in action description

__tests__/main.test.ts, src/IssueProcessor.ts
=> Prevent processing of locked/closed issues/PRs

README.md
Update readme to reference major version, so customers get bug fixes.
=> Update readme to reference major version channel

src/IssueProcessor.ts
=> Fix typo in IssueProcessor.ts

README.md
Adding information table about arguments available in stale action.
=> Add arguments table

src/IssueProcessor.ts
This might help to understand some situations as described in https://github.com/actions/stale/issues/299.
=> Log why issue is not marked as stale

README.md
Adding the option `delete-branch` to the documentation.
=> Add delete branch option

.github/ISSUE_TEMPLATE/feature-request.md
=> chore(issue): add a feature request template when opening an issue

README.md
syntax highlighting with the yaml code chunk and so those that copy/paste the code don't have a breakage
=> use YAML comment syntax for comment in code chunk

CHANGELOG.md, dist/index.js
=> Prep for v4

README.md
release was published but usage examples were not be edited
default configs just work
=> docs(readme): using v4

CHANGELOG.md
=> docs(changelog): adapt config description

README.md
missing description
closes #529
=> docs(readme): add branch hint

.github/workflows/check-dist.yml
We need to make this changes for proper validation. Otherwise `check-dist.yml` is always true
=> Fix check-dist.yml

package-lock.json
=> Update package.lock version

dist/index.js, package-lock.json
=> Update actions core to 1.9.1

CHANGELOG.md, package-lock.json, package.json
#874 introduced a breaking change for exempt items. We are releasing a major version (v7) to not break existing versions.
=> draft release for v7.0.0

README.md
Switch examples in the `README.md` file to reference the v7 release instead of the previous v6 release.
No issue created
=> Switch examples to reference the v7 release

dist/index.js, src/classes/issues-processor.ts, src/classes/rate-limit.ts, src/interfaces/rate-limit.ts, src/main.ts
Log github api rate info
[Sample build](https://github.com/akv-demo/test-stale/actions/runs/5257429320/jobs/9500195867)
[link to the related issue.](https://github.com/actions/stale/issues/1029#issuecomment-1587449869)
=> Add RateLimit

README.md
Change `actions/stale@v8` to `actions/stale@v9` in README.md due to release new version.
=> Docs: Update `actions/stale@v9` on README.md
