src/main.ts

The parameters and variables names make it seem like this is the intended behavior.

Fix wasLastUpdatedBefore to be in days, not hours

---

action.yml
src/main.ts

This is to address https://github.com/actions/stale/issues/18

Add only-labels option

---

action.yml

The `only-labels` description was missing the closing tag `'`.

Fix closing tag in only-labels description

---

dist/index.js
package-lock.json
package.json
src/IssueProcessor.ts

When an `Error` type is thrown instead of a `string`, the command  `core.error(error)` itself would fail, which would mask the real error.  This generally results in an error that is described in https://github.com/actions/toolkit/issues/398.
This bug has been fixed in 1.2.4 of `@actions/core`, so let's just use that version.

Fix for logging error types instead of strings in the main try/catch

---

dist/index.js
package-lock.json
package.json

This adds support for running against GHES by using [v2.2.0](https://github.com/actions/toolkit/blob/master/packages/github/RELEASES.md#220) of `@actions/github`. The details of connecting to a GHES instance or github.com are handled internally in the client, so no code changes in this action are necessary.
Tested by pushing this version of the action to an "actions" org on the GHES instance.  I also needed to set `NODE_TLS_REJECT_UNAUTHORIZED = 0` temporarily in the action to get around my self-signed (or otherwise not trusted) server cert.

Bumping actions/github to 2.2.0

---

__tests__/main.test.ts
src/IssueProcessor.ts

This is to ensure we do not close issues before days-before-close has
expired. Without this fix we can encounter a situation where an issue
gets marked as stale and it gets closed immediately without waiting
days-before-close number of days.
If the user still wishes to close the issue immediately after marking
it stale they have the option of doing so by setting days-before-close
to 0 to get the desired effect.
Fixes: #84

Update issue.updated_at if we have just marked an issue stale

---

__tests__/main.test.ts
action.yml
dist/index.js
src/IssueProcessor.ts
src/main.ts

This (hopefully) adds support for posting a comment when closing the issue/pr due to it being stale.
By default it won't post a closure comment, this is the equivalent of the [`closeComment`](https://github.com/tldr-pages/tldr/blob/208327d21a7373591f5024bf52dd1cb9ddee17f2/.github/stale.yml#L21-L26) config in [Stale Bot](https://github.com/probot/stale). However, it can be different for issues and PRs.

Add support for posting comment on closure

---

__tests__/main.test.ts

Primarily because changing the default options shared amongst tests will affect other tests.
Therefore freezing the default options object so it cannot be changed directly, and making sure all tests *copy* the default options before making changes to the resulting object.

Avoid changing default options in tests

---

__tests__/main.test.ts
action.yml
src/IssueProcessor.ts

Previously this action would stop and skip all issues or pull requests it found if no `stale-issue-message | stale-pr-message` option had been configured.
In practise that meant this action could not be used in repositories where the maintainers would want to manually mark issues and pull requests as stale, instead of this action being responsible for the said marking.
That's what these changes allows for, maintainers being responsible for marking, but still want help from this action to close those issues or pull requests X days after they got manually marked as stale by labelling them.
Configuring `days-before-stale: -1` will activate that behaviour, inspired by how `days-before-close: -1` works already.
Would that sound like a good fit for this action by any chance?

Allow for issues/PRs to be closed after manually being marked as stale

---

__tests__/main.test.ts
action.yml
dist/index.js
src/IssueProcessor.ts
src/main.ts

Fixes https://github.com/actions/stale/issues/78
This introduces two new flags `skip-stale-issue-message` and `skip-stale-pr-message` which would skip the message addition if these are set to true.
They are backward compatible as empty `stale-issue-message` or `stale-pr-message` will take precedence over them.
Regarding the tests, I had to mock a private method in order to test this. Ideally I would mock the methods on the github client but all tests seem to be running in debug mode so I didn't do that. If you have a better proposal for adding tests for this, I would be happy to change this.

feat: add skip-stale-pr-message and skip-stale-issue-message

---

src/IssueProcessor.ts

Typo in `IssueProcessor.js`: a closing parenthesis is missing.

Fix missing parenthesis

---

.gitignore
jest.config.js
package-lock.json
package.json
src/IssueProcessor.ts
src/functions/is-labeled.spec.ts
src/functions/is-labeled.ts
src/functions/labels-to-list.spec.ts
src/functions/labels-to-list.ts

@hross since the tests were not handling the case on error I am not sure that this changes really fix the problem but I strongly think that this was related to the locale string stuff.
Using instead deburr from LoDash seems a good thing but once again I count on you to tell me if you also think that this is right.
Fixes #98.

fix(label): allow to use spaces inside the labels

---

__tests__/main.test.ts
action.yml
src/IssueProcessor.ts
src/main.ts

Closes #57 
1. Setup PR which has `delete-branch` enabled https://github.com/alexbrazier/stale/pull/2
2. Verified it closed and deleted the test PR https://github.com/alexbrazier/stale/pull/1

feat: Add `delete-branch` option to delete PR branches after closing

---

__tests__/main.test.ts
src/IssueProcessor.ts
src/functions/is-labeled.ts

Remove the `encodeURIComponent` when calling the GitHub API to remove a label.
The documentation is not specifying anything regarding special comments so it could work but I was not able to test it.
Fixes #173.

fix(remove-label): do not encode the label to make sure to remove it

---

action.yml

This action doesn't apply exempt labels, it reads them.

Clarify significance of the exempt-* config knobs

---

__tests__/main.test.ts
dist/index.js
src/IssueProcessor.ts

Hi there, [Homebrew](https://github.com/Homebrew/brew) maintainer here. We were recently in the market for a new way to monitor stale issues (our existing configuration stopped working) and figured that this was a great solution. So far, we've only had one minor hiccup that I have aimed to fix in this PR.
This has been reported a few times before, but our issue revolves around the fact that the stale action checks for comments that are not made by a bot or `context.actor` (which is the user who most recently modified the workflow). I am aware of one attempt at removing this in https://github.com/actions/stale/pull/192. The [response](https://github.com/actions/stale/pull/192#issuecomment-731124617) given in that PR makes sense to me:
> The user who set up the schedule will be the "bot". …

Determine actor from PAT if possible

---

.github/workflows/codeql.yml

`git checkout HEAD^2` is no longer necessary.

Remove an unnecessary step from codeql.yml

---

__tests__/main.test.ts
src/IssueProcessor.ts

When different stale period is used for issues and pull requests, this code uses wrong one.
This was probably missed in https://github.com/actions/stale/pull/224
Fixes #299
This is not tested at all, but I hope the fix is correct.

Fixed should be stale condition

---

README.md

Not tested but feels like a typo?
Or if we keep the title it `exempt` feels more approriate:
exempt-issue-labels: 'roadmap'
exempt-pr-labels: 'roadmap'

Typo in how to perform check for specific labels

---

README.md
action.yml

docs(overhaul): provide a very detailed documentation for the options

---

README.md

@luketomlinson I think that we don't even need to alter something in the default config due to the PR removing the skip comment options https://github.com/actions/stale/pull/457
Closes #414

docs(readme): add a summary for the default behaviour

---

.github/workflows/stale.yml
.github/workflows/test.yml

Receiving the messages also for the action that is constantly executed.
follow up for #458

🎨 Print outputs

---

dist/index.js
src/classes/issues-processor.ts
src/enums/option.ts

FYI, you can read the commits to have a better description.
Closes #462
Closes #461

chore(logs): add more logs and better dry-run

---

__tests__/constants/default-processor-options.ts
__tests__/operations-per-run.spec.ts
dist/index.js
src/classes/issues-processor.ts
src/classes/statistics.ts

fix(operations): fail fast the current batch to respect the operations limit

---

README.md
__tests__/constants/default-processor-options.ts
__tests__/main.spec.ts
dist/index.js
src/classes/issue.spec.ts
src/classes/issues-processor.ts
src/enums/option.ts
src/interfaces/issues-processor-options.ts
src/main.ts

Fixes https://github.com/actions/stale/issues/460
Add support for:
- labels-to-remove-when-unstale
- labels-to-add-when-unstale
In order to prevent scenarios like [this](https://github.com/actions/stale/issues/288) and to reduce the amount of upkeep required for maintainers, allow the action to remove/add labels to prevent marking issues stale over and over again. 
Example of an ideal scenario is this:
1. User submits issue
2. We respond and need author feedback, apply that label
3. Issue goes stale via automation
4. Author (or someone else with the same issue) responds suggesting it's still an issue
5. Automation should remove the `needs-author-feedback` label and add some `author-responded` or `needs-dev-response` label
This allows automation to ONLY run on `needs-author-feedback` …

Add support for adding & removing labels when no longer stale

---

README.md
__tests__/constants/default-processor-options.ts
dist/index.js
src/classes/issues-processor.ts

fix(dry-run): forbid mutations in dry-run

---

README.md

Everybody knows which permissions are required for the action.
closes #491

📝 Add requested permissions

---

__tests__/any-of-labels.spec.ts
__tests__/assignees.spec.ts
__tests__/classes/issues-processor-mock.ts
__tests__/main.spec.ts
__tests__/milestones.spec.ts
__tests__/only-labels.spec.ts
__tests__/operations-per-run.spec.ts
__tests__/remove-stale-when-updated.spec.ts
dist/index.js
src/classes/issues-processor.ts
src/interfaces/comment.ts

Fixes #509 
Fixes #441 
Fixes #518

Filter comments by content instead of actor

---

action.yml
dist/index.js
src/classes/issues-processor.ts
src/functions/clean-label.ts

add missing inputs to action.yml

---

README.md

Closes #561 . Just prevents quick copy-paste from anyone not double checking and accidentally setting the wrong start date.

docs(readme): fix a wrong ISO format date example

---

README.md
__tests__/classes/issues-processor-mock.ts
__tests__/constants/default-processor-options.ts
__tests__/exempt-draft-pr.spec.ts
action.yml
dist/index.js
src/classes/exempt-draft-pull-request.ts
src/classes/issue.spec.ts
src/classes/issues-processor.ts
src/enums/option.ts
src/interfaces/issues-processor-options.ts
src/interfaces/pull-request.ts
src/main.ts

Closes https://github.com/actions/stale/issues/36 (even if already closed).
See https://github.com/actions/stale/issues/36#issuecomment-889249688.

feat(draft-pr): add new option to not process PRs which are in draft

---

README.md
__tests__/main.spec.ts
dist/index.js
src/classes/issues-processor.ts
src/classes/statistics.ts

docs(stale-issue-comment): update the docs to remove that omitting the option will not send a message

---

__tests__/classes/issues-processor-mock.ts
dist/index.js
src/classes/issues-processor.ts

fixes https://github.com/actions/stale/issues/661
I wanted to add some unit tests and fix the problem TDD-style, but this proved to be tough given the way that `issues-processor` is currently mocked out, so I gave up. Related, I also think that some of the tests in `https://github.com/actions/stale/blob/main/__tests__/operations-per-run.spec.ts` are making incorrect assertions because some of the methods that increment operation count get mocked. This all seems pretty fixable, but I think that would require more churn than I'm comfortable introducing right now, so if tests are required for this PR I think I'll leave it to someone else.

Fix per issue operation count

---

.github/dependabot.yml

Checking daily results in a lot of closed PRs because new PRs supersede them before they are reviewed and merged.

Change NPM version update interval (daily → weekly)

---

dist/index.js
src/classes/issues-processor.ts

- Fix spaces in `issues-processor.ts`

Fix spaces in `issues-processor.ts`

---

dist/index.js
src/classes/issues-processor.ts

The existing logic for `remove-stale-when-updated` only considers presence of comments, ignoring the presence of any other kind of  update.
This fixes it so it follows the documented behaviour for that setting.
There is no effect from this change on tests (all pass). I suspect that the tests simply do not cover the case of updates, only comments; the new logic is equivalent to the old one for the case of new comments.
I would have included new tests to add to the coverage, but I have no idea how to achieve that as this is my first time ever touching TypeScript code.
Fixes #715

[Bugfix] Remove stale when updated without comment

---

README.md
__tests__/constants/default-processor-options.ts
dist/index.js
src/classes/issue.spec.ts
src/classes/issues-processor.ts
src/enums/option.ts
src/interfaces/issues-processor-options.ts
src/main.ts

Adds an option `close-issue-reason`, which can be used to close stale issues as ["not planned"](https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/) (a relatively new GitHub feature).
I tested the `state_reason: "not_planned"` option by making manual calls to the REST API (unfortunately it is not currently listed in the REST API documentation).
Resolves https://github.com/actions/stale/issues/744

Add close-issue-reason option

---

README.md

As people becoming able to use v5 in the marketplace, I guess it's better to update the guideline as well.

docs: update example with new version of stale

---

action.yml

Add the missing `close-issue-reason` option to the `action.yml`
It's great that #764 has added the `close-issue-reason` option to allow closing a stale issue with a specified reason. But it seems this new option is missing in the `action.yml` configuration file, so a warning will be generated when running the action and the stale issues can't be closed with the expected reason.
Please refer to the following action for more details: https://github.com/apache/echarts/actions/runs/2618863511
---
Oh... I'm sorry I just found the feature hasn't been released. Perhaps, can we publish a new version for it?

fix(options): add missing `close-issue-reason` option

---

dist/index.js
src/classes/issues-processor.ts

When we introduced #717, we inadvertently introduced a bug that would occur when `days-before-close` > `days-before-stale`. 
`days-before-stale: 0` and `days-before-close: 30`
Every issue should be `stale` in this scenario and the `stale` label would be applied as expected. The problem was is that the action would look back `30` days and ALWAYS see an update and immediately remove the stale label. 
My changes change the logic that can potentially "un-stale" an issue. Rather than check for an update in the last `days-before-close` days (e.g. 30), I check if the update occurred AFTER the stale date. This is subtle, but caused big issues for actions when `days-before-close` > `days-before-stale`
fixes #774

Fix issue when days-before-close is more than days-before-stale

---

README.md

Updating readme to include a permission that is required for `delete-branch` option that is missing from the readme. Configuring this workflow with that additional permission should prevent issues like https://github.com/actions/stale/issues/587 from being raised again (https://github.com/actions/stale/issues/587 wasn't actually resolved, just closed by a bot due to inactivity).
I have recently implemented this workflow in a repository configured with `delete-branch: true`. After the initial wait period, it started closing stale pull requests, but kept failing when trying to delete corresponding branches with the following error `Error when deleting the branch "BRANCH_NAME" from pull request: Resource not accessible by integration`. 
Searching for answers I found the issue …

docs(readme): add missing permission for delete-branch option in readme

---

__tests__/constants/default-processor-options.ts
__tests__/main.spec.ts
dist/index.js
src/classes/issue.spec.ts
src/classes/issues-processor.ts
src/interfaces/issues-processor-options.ts
src/main.ts

- Add new boolean option `include-only-assigned`. 
New option `include-only-assigned` enables users to process only issues/PRs that are already assigned. If there is no assignees and this option is set, issue will not be processed.
Resolves https://github.com/actions/stale/issues/596

Issue 596/include only assigned

---

README.md
__tests__/constants/default-processor-options.ts
action.yml

which defaulted to `completed`) This closes the issue as 'not planned' on GitHub rather than 'completed'
- I'm happy to drop this if it's an issue - unsure on PR requirements for this repo
GitHub introduced an additional close reason 'Close as not planned':
https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
'stale' is a use case for this close reason and makes sense as a default for this action
Fixes https://github.com/actions/stale/issues/789
Feature added: https://github.com/actions/stale/commit/06d2a3904b77e3b34b74319855eebe4627488d19
Updated: https://github.com/actions/stale/commit/aaab997ccea19e4bbf31972dde2a627199681ea4

fix(options)!: Make `not_planned` the default `close-issue-reason`

---

CHANGELOG.md
README.md

#789 introduced a breaking change for the default `close-issue-reason`. We are releasing a major version (v6) to not break existing versions.

Update changelog for v6.0.0

---

__tests__/main.spec.ts
dist/index.js
src/main.ts

Allow daysBeforeStale options to be float

---

.github/workflows/stale.yml
.github/workflows/test.yml

The current workflows are failing in the repo, they are stuck in the `Print outputs` step. After debugging them using [act](https://github.com/nektos/act), I realized the outputs were printed wrong, repeating all the properties from each array element over and over again, such as:
```
[operations:{_operationsConsumed:4},operations:{_operationsConsumed:4}] 
[operations:{_operationsConsumed:4},_options:repoToken:***] 
[operations:{_operationsConsumed:4},_options:staleIssueMessage:This issue is stale] 
[operations:{_operationsConsumed:4},_options:stalePrMessage:This PR is stale] 
[operations:{_operationsConsumed:4},_options:closeIssueMessage:] 
[operations:{_operationsConsumed:4},_options:closePrMessage:] 
...
```
The error is more notorious now and causes the workflows failing due to we …

fix print outputs step in existing workflows

---

.licenses/npm/semver.dep.yml
dist/index.js
package-lock.json
package.json
tsconfig.json

In the scope of this PR, some versions of development dependencies were bumped. This bump was inspired by dependabot's PRs:
- https://github.com/actions/stale/pull/911
- https://github.com/actions/stale/pull/910
- https://github.com/actions/stale/pull/909
- https://github.com/actions/stale/pull/885
- https://github.com/actions/stale/pull/868
Some of the dependencies like **jest-circus** or **typescript** also required the other (related) dependencies to be updated, so it was also done. As previously the typescript 4.3.2 was used, during the switch to 4.9.4 `tsconfig.json` file had to be updated to incorporate the setting: `useUnknownInCatchVariables: false` which helps to solve this [peculiarity](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#using-un …

Bump npm dependencies

---

__tests__/exempt-draft-pr.spec.ts
dist/index.js
src/classes/issues-processor.ts
src/interfaces/pull-request.ts

Handle an attempt of the deleting a branch in a forked repo
When the action runs against the repo that has PRs from the forked repo it attempted to delete the branch from the fork repo and failed.
The PR fix this.
[link to the related issue.](https://github.com/actions/stale/issues/881)

Skip deleting the branch in the upstream of a forked repo

---

dist/index.js
src/classes/state/state-cache-storage.ts
src/classes/state/state.ts

Use https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#list-github-actions-caches-for-a-repository
to check if the cache exists and skip the restore if it does not.
Logging is also changed, since state recovery can only fail because of the error. 
e2e run: https://github.com/akv-demo/test-stale/actions/runs/5615517213/job/15215993242
[link to the original issue.](https://github.com/github/c2c-actions-akvelon/issues/32)
[link to the related issue.](https://github.com/actions/runner-images-internal/issues/5239)

Do not restore state if the cache does not exist

---

.licenses/npm/semver-7.5.4.dep.yml
package-lock.json
package.json

In the scope of this PR is a simple Semver version update (from `7.5.3` to `7.5.4`). I mostly created this PR because I noticed after looking into https://github.com/actions/stale/pull/1011 that `package.json` still had an old version (`7.3.5`) while the ones in `package-lock` were bumped to `7.5.1`. Potentially, due to the fact that the PR above is old, it created some merge conflicts, so doing it this way was probably more efficient.
Unit tests were ran prior to committing and no errors were thrown.
[Add link to the related issue.](https://github.com/actions/stale/pull/1011)

Update Semver to 7.5.4 and add licensing

---

README.md
dist/index.js
src/classes/state/state-cache-storage.ts

Current main branch produces CacheNotFoundException when trying to delete non-existing cache.
To fix it the PR adds extra check if the cache exists. 
[link to the related issue.](https://github.com/github/c2c-actions-akvelon/issues/32)

Fix delete cache

---

CHANGELOG.md

It was observed that the CHANGELOG.MD file was not updated for the recent releases. This PR includes changes to the CHANGELOG.MD file to reflect the recent releases (actions/stale v8 and v9).
Following is the related issue #1101 

Updates to CHANGELOG.MD for recent releases
